"""Match rule edges (§10.5).

Candidate pairs are never generated by a cross-join: edges come from
``groupBy(namespace, value_hash)`` over the identifier long table (a
shuffle-and-group, O(N log N)), then a join restricted to that tiny group --
never an O(N^2) global comparison.
"""
from __future__ import annotations

from pyspark.sql import DataFrame, Window
from pyspark.sql import functions as F

AUTHORITATIVE_NAMESPACES = ("crm_id", "loyalty_id", "app_user_id")


def _record_key(df: DataFrame) -> DataFrame:
    return df.withColumn("source_record_key", F.concat_ws(":", "source_system", "source_record_id"))


def _block_pairs(specific: DataFrame, namespaces: list[str]) -> DataFrame:
    scoped = specific.filter(F.col("identity_namespace").isin(namespaces))
    a = scoped.alias("a")
    b = scoped.alias("b")
    return (
        a.join(b, on=[F.col("a.identity_namespace") == F.col("b.identity_namespace"),
                      F.col("a.value_hash") == F.col("b.value_hash"),
                      F.col("a.source_record_key") < F.col("b.source_record_key")])
        .select(
            F.col("a.source_record_key").alias("record_a"),
            F.col("b.source_record_key").alias("record_b"),
            F.col("a.identity_namespace").alias("namespace"),
            F.col("a.value_masked").alias("value_masked"),
        )
    )


def _surname_compatible(a_last, a_first, b_last, b_first) -> "F.Column":
    same_surname = a_last == b_last
    same_first = (a_first == b_first) | (F.substring(a_first, 1, 1) == F.substring(b_first, 1, 1))
    return same_surname & same_first


def build_edges(screened: DataFrame, rules_cfg: dict, person_attrs: DataFrame | None) -> DataFrame:
    """screened: output of screening.screen_identifiers (has is_screened, value_hash, value_masked)."""
    df = _record_key(screened)
    specific = df.filter(~F.col("is_screened"))

    edges = []

    r01 = rules_cfg_lookup(rules_cfg, "R-01")
    pairs = _block_pairs(specific, list(AUTHORITATIVE_NAMESPACES))
    edges.append(pairs.withColumn("rule_id", F.lit("R-01")).withColumn("confidence", F.lit(r01["confidence"])))

    r02 = rules_cfg_lookup(rules_cfg, "R-02")
    pairs = _block_pairs(specific, ["email"])
    edges.append(pairs.withColumn("rule_id", F.lit("R-02")).withColumn("confidence", F.lit(r02["confidence"])))

    r03 = rules_cfg_lookup(rules_cfg, "R-03")
    phone_pairs = _block_pairs(specific, ["phone"])
    edges.append(phone_pairs.withColumn("rule_id", F.lit("R-03")).withColumn("confidence", F.lit(r03["confidence"])))

    if person_attrs is not None and "full_name_norm" in person_attrs.columns:
        r04 = rules_cfg_lookup(rules_cfg, "R-04")
        phone_specific = specific.filter(F.col("identity_namespace") == "phone")
        a = phone_specific.alias("a").join(
            person_attrs.select(F.concat_ws(":", "source_system", "source_record_id").alias("record_key"),
                                 "first_name_norm", "last_name_norm").alias("pa_a"),
            F.col("a.source_record_key") == F.col("pa_a.record_key"))
        b = phone_specific.alias("b").join(
            person_attrs.select(F.concat_ws(":", "source_system", "source_record_id").alias("record_key"),
                                 "first_name_norm", "last_name_norm").alias("pa_b"),
            F.col("b.source_record_key") == F.col("pa_b.record_key"))
        name_pairs = (
            a.join(b, on=[F.col("a.value_hash") == F.col("b.value_hash"),
                          F.col("a.source_record_key") < F.col("b.source_record_key")])
            .filter(_surname_compatible(F.col("pa_a.last_name_norm"), F.col("pa_a.first_name_norm"),
                                         F.col("pa_b.last_name_norm"), F.col("pa_b.first_name_norm")))
            .select(F.col("a.source_record_key").alias("record_a"),
                    F.col("b.source_record_key").alias("record_b"),
                    F.lit("phone").alias("namespace"),
                    F.col("a.value_masked").alias("value_masked"))
        )
        edges.append(name_pairs.withColumn("rule_id", F.lit("R-04")).withColumn("confidence", F.lit(r04["confidence"])))

    all_edges = edges[0]
    for e in edges[1:]:
        all_edges = all_edges.unionByName(e)

    # keep the highest-precedence (lowest rule number / highest confidence) edge per pair
    w = F.row_number().over(Window.partitionBy("record_a", "record_b").orderBy(F.col("confidence").desc()))
    return all_edges.withColumn("_rn", w).filter(F.col("_rn") == 1).drop("_rn")


def rules_cfg_lookup(rules_cfg: dict, rule_id: str) -> dict:
    for r in rules_cfg.get("rules", []):
        if r["id"] == rule_id:
            return r
    raise KeyError(rule_id)
